import {
    createTheme,
    responsiveFontSizes,
    ThemeProvider,
} from '@mui/material/styles';
import Typography from '@mui/material/Typography';
import Box from '@mui/material/Box'

let theme = createTheme();
theme = responsiveFontSizes(theme);

export default function Body() {
    return (

        <Box sx={{ padding: "5% 5% 8% 8%", flexGrow: 1, color: '#555' }}>
            <ThemeProvider theme={theme}>

                <Typography sx={{ marginBottom: '10px' }}>
                    Nostrud cupidatat ea adipisicing irure sit eiusmod id adipisicing anim Pariatur et aute minim laboris consectetur. Duis ad labore commodo commodo consequat nulla. Non duis duis laborum culpa commodo velit.Pariatur amet veniam duis proident eiusmod sit excepteur. Consequat amet mollit voluptate sit pariatur enim id ea. Ad nulla in anim ut laborum et exercitation consequat nisi sit.Ut occaecat mollit magna tempor ex in consectetur enim ad anim ex. Sunt id cupidatat pariatur elit ad magna ad. Enim in mollit fugiat veniam eiusmod ullamco adipisicing id duis cillum excepteur minim dolor amet. Mollit cupidatat amet sunt sunt pariatur occaecat laborum amet aute. Aliquip aliqua reprehenderit voluptate non proident proident veniam fugiat ut officia. Quis excepteur reprehenderit quis sit sit eiusmod aute deserunt est aliqua esse duis eu officia. Laborum cupidatat nulla est aliqua pariatur tempor laboris aute.Ipsum sit mollit veniam cillum ad veniam reprehenderit amet do. Consequat veniam tempor aute officia aute exercitation. Non fugiat magna deserunt amet do commodo adipisicing commodo deserunt fugiat ex ad tempor reprehenderit. Laboris exercitation id Lorem veniam qui deserunt Lorem est aliqua in aliquip. Commodo excepteur aliqua magna eu quis sit est. Esse voluptate excepteur tempor occaecat officia cupidatat exercitation adipisicing aliquip elit. exercitation adipisicing commodo reprehenderit reprehenderit. Duis sit nostrud aliquip incididunt ullamco sunt nisi. Aliqua nostrud velit est ad laboris eiusmod aliquip laborum consectetur anim laboris cillum dolor. Commodo reprehenderit et mollit sunt est culpa eiusmod proident laborum minim enim ex. Voluptate ut nulla incididunt in ex tempor culpa. Magna consectetur commodo et commodo id eiusmod excepteur do.
                </Typography>
                <Typography sx={{ marginBottom: '10px' }}>
                    Eiusmod velit et eu quis laboris sit ea. Labore et sunt qui nulla id velit Lorem cillum veniam aliquip nisi. Nisi veniam mollit eu do minim quis anim enim nisi do enim amet enim.Est exercitation proident elit culpa sit pariatur id consectetur proident amet eu nisi ea. Anim est non voluptate elit quis voluptate minim elit nisi. Id officia Lorem occaecat laboris irure consectetur consectetur sunt. Ullamco pariatur pariatur in consectetur incididunt non proident deserunt consequat cillum non.Consequat occaecat nostrud sit consectetur nisi cillum sint consequat ut. Ea sunt eiusmod do proident aliqua tempor. Reprehenderit dolor in eu in cupidatat adipisicing.Dolore exercitation consectetur sunt ea aliqua Lorem cupidatat fugiat ea labore. Veniam minim dolore ad et aute anim labore cillum. Nostrud irure non ea reprehenderit aute nulla aliqua magna aliqua aliqua aliqua. Duis dolor laborum dolore elit incididunt nulla laborum consequat laboris sint. Aliqua aute et exercitation sit nulla anim ex laborum ea consectetur. Duis irure labore elit qui labore aliqua.Occaecat occaecat velit et est pariatur laborum anim dolore et aliqua aliqua. Culpa exercitation nostrud est laboris quis reprehenderit exercitation ipsum duis laboris non. Elit dolore minim dolore ex non fugiat adipisicing dolore do dolor.Elit consequat laborum sunt reprehenderit magna aliqua excepteur mollit. Velit cillum sint non irure eiusmod. Qui aliquip esse minim pariatur est. Exercitation magna et occaecat exercitation officia. Aute non ad ipsum excepteur. Adipisicing eiusmod est occaecat et minim cillum officia aliqua fugiat culpa cupidatat sint cupidatat. Aliqua elit cupidatat laboris dolore culpa magna fugiat velit est.
                </Typography>
                <Typography sx={{ marginBottom: '10px' }}>
                    Eiusmod velit et eu quis laboris sit ea. Labore et sunt qui nulla id velit Lorem cillum veniam aliquip nisi. Nisi veniam mollit eu do minim quis anim enim nisi do enim amet enim.Est exercitation proident elit culpa sit pariatur id consectetur proident amet eu nisi ea. Anim est non voluptate elit quis voluptate minim elit nisi. Id officia Lorem occaecat laboris irure consectetur consectetur sunt. Ullamco pariatur pariatur in consectetur incididunt non proident deserunt consequat cillum non.Consequat occaecat nostrud sit consectetur nisi cillum sint consequat ut. Ea sunt eiusmod do proident aliqua tempor. Reprehenderit dolor in eu in cupidatat adipisicing.Dolore exercitation consectetur sunt ea aliqua Lorem cupidatat fugiat ea labore. Veniam minim dolore ad et aute anim labore cillum. Nostrud irure non ea reprehenderit aute nulla aliqua magna aliqua aliqua aliqua. Duis dolor laborum dolore elit incididunt nulla laborum consequat laboris sint. Aliqua aute et exercitation sit nulla anim ex laborum ea consectetur. Duis irure labore elit qui labore aliqua.Occaecat occaecat velit et est pariatur laborum anim dolore et aliqua aliqua. Culpa exercitation nostrud est laboris quis reprehenderit exercitation ipsum duis laboris non. Elit dolore minim dolore ex non fugiat adipisicing dolore do dolor.Elit consequat laborum sunt reprehenderit magna aliqua excepteur mollit. Velit cillum sint non irure eiusmod. Qui aliquip esse minim pariatur est. Exercitation magna et occaecat exercitation officia. Aute non ad ipsum excepteur. Adipisicing eiusmod est occaecat et minim cillum officia aliqua fugiat culpa cupidatat sint cupidatat. Aliqua elit cupidatat laboris dolore culpa magna fugiat velit est.
                </Typography>
                <Typography sx={{ marginBottom: '10px' }}>
                    Eiusmod velit et eu quis laboris sit ea. Labore et sunt qui nulla id velit Lorem cillum veniam aliquip nisi. Nisi veniam mollit eu do minim quis anim enim nisi do enim amet enim.Est exercitation proident elit culpa sit pariatur id consectetur proident amet eu nisi ea. Anim est non voluptate elit quis voluptate minim elit nisi. Id officia Lorem occaecat laboris irure consectetur consectetur sunt. Ullamco pariatur pariatur in consectetur incididunt non proident deserunt consequat cillum non.Consequat occaecat nostrud sit consectetur nisi cillum sint consequat ut. Ea sunt eiusmod do proident aliqua tempor. Reprehenderit dolor in eu in cupidatat adipisicing.Dolore exercitation consectetur sunt ea aliqua Lorem cupidatat fugiat ea labore. Veniam minim dolore ad et aute anim labore cillum. Nostrud irure non ea reprehenderit aute nulla aliqua magna aliqua aliqua aliqua. Duis dolor laborum dolore elit incididunt nulla laborum consequat laboris sint. Aliqua aute et exercitation sit nulla anim ex laborum ea consectetur. Duis irure labore elit qui labore aliqua.Occaecat occaecat velit et est pariatur laborum anim dolore et aliqua aliqua. Culpa exercitation nostrud est laboris quis reprehenderit exercitation ipsum duis laboris non. Elit dolore minim dolore ex non fugiat adipisicing dolore do dolor.Elit consequat laborum sunt reprehenderit magna aliqua excepteur mollit. Velit cillum sint non irure eiusmod. Qui aliquip esse minim pariatur est. Exercitation magna et occaecat exercitation officia. Aute non ad ipsum excepteur. Adipisicing eiusmod est occaecat et minim cillum officia aliqua fugiat culpa cupidatat sint cupidatat. Aliqua elit cupidatat laboris dolore culpa magna fugiat velit est.
                </Typography>
                <Typography sx={{ marginBottom: '10px' }}>
                    Eiusmod velit et eu quis laboris sit ea. Labore et sunt qui nulla id velit Lorem cillum veniam aliquip nisi. Nisi veniam mollit eu do minim quis anim enim nisi do enim amet enim.Est exercitation proident elit culpa sit pariatur id consectetur proident amet eu nisi ea. Anim est non voluptate elit quis voluptate minim elit nisi. Id officia Lorem occaecat laboris irure consectetur consectetur sunt. Ullamco pariatur pariatur in consectetur incididunt non proident deserunt consequat cillum non.Consequat occaecat nostrud sit consectetur nisi cillum sint consequat ut. Ea sunt eiusmod do proident aliqua tempor. Reprehenderit dolor in eu in cupidatat adipisicing.Dolore exercitation consectetur sunt ea aliqua Lorem cupidatat fugiat ea labore. Veniam minim dolore ad et aute anim labore cillum. Nostrud irure non ea reprehenderit aute nulla aliqua magna aliqua aliqua aliqua. Duis dolor laborum dolore elit incididunt nulla laborum consequat laboris sint. Aliqua aute et exercitation sit nulla anim ex laborum ea consectetur. Duis irure labore elit qui labore aliqua.Occaecat occaecat velit et est pariatur laborum anim dolore et aliqua aliqua. Culpa exercitation nostrud est laboris quis reprehenderit exercitation ipsum duis laboris non. Elit dolore minim dolore ex non fugiat adipisicing dolore do dolor.Elit consequat laborum sunt reprehenderit magna aliqua excepteur mollit. Velit cillum sint non irure eiusmod. Qui aliquip esse minim pariatur est. Exercitation magna et occaecat exercitation officia. Aute non ad ipsum excepteur. Adipisicing eiusmod est occaecat et minim cillum officia aliqua fugiat culpa cupidatat sint cupidatat. Aliqua elit cupidatat laboris dolore culpa magna fugiat velit est.
                </Typography>
            </ThemeProvider>

        </Box>
    )
}